- name: Convert CustomResource spec to json
  cr_to_json:
    name: "{{ meta.name | default('zuul') }}"
  register: _cr

- name: Convert spec to template input
  json_to_dhall:
    schema: "({{ zuul_app_path }}).Input"
    json: "{{ _cr.result | to_json }}"
  register: _dhall

- include_role:
    name: dhall
  vars:
    expression: |
      {{ kubernetes_deploy_path }}
      (({{ zuul_app_path }}).Application {{ _dhall.result }})
