- name: Convert spec to template input
  json_to_dhall:
    schema: "({{ zuul_app_path }}).Input"
    json: "{{ spec | to_json }}"
  vars:
    spec:
      name: "{{ meta.name | default('zuul') }}"
      merger: "{{ merger | default({}) }}"
      executor: "{{ executor | default({}) }}"
  register: _dhall

- include_role:
    name: dhall
  vars:
    expression: |
      {{ kubernetes_deploy_path }}
      (({{ zuul_app_path }}).Application {{ _dhall.result }})
