apiVersion: v1
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zuul-secret-zuul
    stringData:
      zuul.conf: |
        [gearman]
        server=scheduler
        
        [gearman_server]
        start=true
        
        [zookeeper]
        hosts=zk
        
        [merger]
        git_user_email=zuul@localhost
        git_user_name=Zuul
        
        [scheduler]
        tenant_config=/etc/zuul-scheduler/main.yaml
        
        [web]
        listen_address=0.0.0.0
        root=http://web:9000
        
        [executor]
        private_key_file=/etc/zuul-executor/id_rsa
        manage_ansible=false
        
        [connection "sql"]
        driver=sql
        dburi=postgresql://zuul:super-secret@db/zuul
        
        [connection opendev.org]
        driver=git
        baseurl=https://opendev.org
        
        [connection review.rdoproject.org]
        driver=gerrit
        server=review.rdoproject.org
        sshkey=/etc/zuul-gerrit-review.rdoproject.org/id_rsa
        user=zuul
        baseurl=https://review.rdoproject.org/r/
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/component: db
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: db
    spec:
      ports:
        - name: pg
          port: 5432
          protocol: TCP
          targetPort: pg
      selector:
        app.kubernetes.io/component: db
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/component: zk
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: zk
    spec:
      ports:
        - name: zk
          port: 2181
          protocol: TCP
          targetPort: zk
      selector:
        app.kubernetes.io/component: zk
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/component: executor
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: executor
    spec:
      ports:
        - name: finger
          port: 7900
          protocol: TCP
          targetPort: finger
      selector:
        app.kubernetes.io/component: executor
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: web
    spec:
      ports:
        - name: api
          port: 9000
          protocol: TCP
          targetPort: api
      selector:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: scheduler
    spec:
      ports:
        - name: gearman
          port: 4730
          protocol: TCP
          targetPort: gearman
      selector:
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      type: ClusterIP
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: zuul-web
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: web
          app.kubernetes.io/instance: zuul
          app.kubernetes.io/name: zuul
          app.kubernetes.io/part-of: zuul
      template:
        metadata:
          labels:
            app.kubernetes.io/component: web
            app.kubernetes.io/instance: zuul
            app.kubernetes.io/name: zuul
            app.kubernetes.io/part-of: zuul
          name: web
        spec:
          containers:
            - args:
                - zuul-web
                - "-d"
              image: quay.io/software-factory/zuul-web:3.4
              imagePullPolicy: IfNotPresent
              name: web
              ports:
                - containerPort: 9000
                  name: api
              volumeMounts:
                - mountPath: /etc/zuul
                  name: zuul
          initContainers:
            - args:
                - sh
                - "-c"
                - "until python -c 'import socket, sys; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((sys.argv[1], 4730))' scheduler 2>/dev/null; do echo 'waiting for scheduler:4730'; sleep 1; done"
              image: quay.io/software-factory/zuul:3.4
              imagePullPolicy: IfNotPresent
              name: web-init0
              ports:
                - containerPort: 9000
                  name: api
              volumeMounts:
                - mountPath: /etc/zuul
                  name: zuul
          volumes:
            - name: zuul
              secret:
                secretName: zuul-secret-zuul
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        app.kubernetes.io/component: db
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: zuul-db
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: db
          app.kubernetes.io/instance: zuul
          app.kubernetes.io/name: zuul
          app.kubernetes.io/part-of: zuul
      serviceName: db
      template:
        metadata:
          labels:
            app.kubernetes.io/component: db
            app.kubernetes.io/instance: zuul
            app.kubernetes.io/name: zuul
            app.kubernetes.io/part-of: zuul
          name: db
        spec:
          containers:
            - env:
                - name: POSTGRES_PASSWORD
                  value: super-secret
                - name: POSTGRES_USER
                  value: zuul
              image: docker.io/library/postgres:12.1
              imagePullPolicy: IfNotPresent
              name: db
              ports:
                - containerPort: 5432
                  name: pg
      volumeClaimTemplates:
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: zuul-db
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        app.kubernetes.io/component: zk
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: zuul-zk
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: zk
          app.kubernetes.io/instance: zuul
          app.kubernetes.io/name: zuul
          app.kubernetes.io/part-of: zuul
      serviceName: zk
      template:
        metadata:
          labels:
            app.kubernetes.io/component: zk
            app.kubernetes.io/instance: zuul
            app.kubernetes.io/name: zuul
            app.kubernetes.io/part-of: zuul
          name: zk
        spec:
          containers:
            - image: quay.io/software-factory/zookeeper:3.4
              imagePullPolicy: IfNotPresent
              name: zk
              ports:
                - containerPort: 2181
                  name: zk
      volumeClaimTemplates:
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: zuul-zk
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        app.kubernetes.io/component: executor
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: zuul-executor
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: executor
          app.kubernetes.io/instance: zuul
          app.kubernetes.io/name: zuul
          app.kubernetes.io/part-of: zuul
      serviceName: executor
      template:
        metadata:
          labels:
            app.kubernetes.io/component: executor
            app.kubernetes.io/instance: zuul
            app.kubernetes.io/name: zuul
            app.kubernetes.io/part-of: zuul
          name: executor
        spec:
          containers:
            - args:
                - zuul-executor
                - "-d"
              image: quay.io/software-factory/zuul-executor:3.4
              imagePullPolicy: IfNotPresent
              name: executor
              ports:
                - containerPort: 7900
                  name: finger
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /etc/zuul
                  name: zuul
                - mountPath: /etc/zuul-executor
                  name: executor-ssh-key
                - mountPath: /etc/zuul-gerrit-review.rdoproject.org
                  name: rdo-key
                - mountPath: /etc/zuul-github-github.com
                  name: github
          initContainers:
            - args:
                - sh
                - "-c"
                - "until python -c 'import socket, sys; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((sys.argv[1], 4730))' scheduler 2>/dev/null; do echo 'waiting for scheduler:4730'; sleep 1; done"
              image: quay.io/software-factory/zuul:3.4
              imagePullPolicy: IfNotPresent
              name: executor-init0
              ports:
                - containerPort: 7900
                  name: finger
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /etc/zuul
                  name: zuul
                - mountPath: /etc/zuul-executor
                  name: executor-ssh-key
                - mountPath: /etc/zuul-gerrit-review.rdoproject.org
                  name: rdo-key
                - mountPath: /etc/zuul-github-github.com
                  name: github
          volumes:
            - name: zuul
              secret:
                secretName: zuul-secret-zuul
            - name: executor-ssh-key
              secret:
                secretName: executor-ssh-key
            - name: rdo-key
              secret:
                secretName: rdo-key
            - name: github
              secret:
                secretName: github
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: zuul-scheduler
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: scheduler
          app.kubernetes.io/instance: zuul
          app.kubernetes.io/name: zuul
          app.kubernetes.io/part-of: zuul
      serviceName: scheduler
      template:
        metadata:
          labels:
            app.kubernetes.io/component: scheduler
            app.kubernetes.io/instance: zuul
            app.kubernetes.io/name: zuul
            app.kubernetes.io/part-of: zuul
          name: scheduler
        spec:
          containers:
            - args:
                - zuul-scheduler
                - "-d"
              image: quay.io/software-factory/zuul-scheduler:3.4
              imagePullPolicy: IfNotPresent
              name: scheduler
              ports:
                - containerPort: 4730
                  name: gearman
              volumeMounts:
                - mountPath: /etc/zuul
                  name: zuul
                - mountPath: /etc/zuul-scheduler
                  name: zuul-yaml-conf
                - mountPath: /etc/zuul-gerrit-review.rdoproject.org
                  name: rdo-key
                - mountPath: /etc/zuul-github-github.com
                  name: github
          volumes:
            - name: zuul
              secret:
                secretName: zuul-secret-zuul
            - name: zuul-yaml-conf
              secret:
                secretName: zuul-yaml-conf
            - name: rdo-key
              secret:
                secretName: rdo-key
            - name: github
              secret:
                secretName: github
      volumeClaimTemplates:
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: zuul-scheduler
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
  - apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
      name: zuul-web
    spec:
      rules:
        - http:
            paths:
              - backend:
                  serviceName: web
                  servicePort: 9000
                path: /
kind: List
