
- hosts: localhost
  tasks:
    - become: true
      lineinfile:
        line: "127.0.0.2 executor"
        path: /etc/hosts
        regexp: "^127.0.0.2 .*"
    - changed_when: _volume_zuul.stderr
      name: "Get or create volume"
      register: _volume_zuul
      shell: "podman volume inspect zuul-zuul --format \"{{'{{'}}.Mountpoint{{'}}'}}\" || ( podman volume create zuul-zuul && podman volume inspect zuul-zuul --format \"{{'{{'}}.Mountpoint{{'}}'}}\" )"
    - copy:
        content: |
          [gearman]
          server=scheduler
          
          [zookeeper]
          hosts=zk
          
          [merger]
          git_user_email=zuul@zuul
          
          [gearman_server]
          start=true
          
          [scheduler]
          tenant_config=/etc/zuul/main.yaml
          
          [web]
          listen_address=0.0.0.0
          
          [executor]
          private_key_file=/etc/zuul-executor/id_rsa
          
        dest: "{{ _volume_zuul.stdout }}/zuul.conf"
        serole: object_r
        setype: container_file_t
        seuser: system_u
    - command: "podman create --name zuul-executor --privileged --volume=zuul-zuul:/etc/zuul --volume=executor-ssh-key-secret-name:/etc/zuul-executor --network=host quay.io/software-factory/zuul-executor:3.4 \"zuul-executor\" \"-d\""
      name: "Create container"
    - file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
    - name: "Create systemd unit"
      shell: "podman generate systemd --name zuul-executor > {{ ansible_user_dir }}/.config/systemd/user/zuul-executor.service"
    - systemd:
        daemon_reload: true
        name: zuul-executor
        scope: user
        state: started
