
- hosts: localhost
  tasks:
    - become: true
      lineinfile:
        line: "127.0.0.2 db zk executor web scheduler"
        path: /etc/hosts
        regexp: "^127.0.0.2 .*"
    - changed_when: _volume_zuul.stderr
      name: "Get or create volume"
      register: _volume_zuul
      shell: "podman volume inspect zuul-zuul --format \"{{'{{'}}.Mountpoint{{'}}'}}\" || ( podman volume create zuul-zuul && podman volume inspect zuul-zuul --format \"{{'{{'}}.Mountpoint{{'}}'}}\" )"
    - copy:
        content: |
          [gearman]
          server=scheduler
          
          [gearman_server]
          start=true
          
          [zookeeper]
          hosts=zk
          
          [merger]
          git_user_email=zuul@localhost
          git_user_name=Zuul
          
          [scheduler]
          tenant_config=/etc/zuul-scheduler/main.yaml
          
          [web]
          listen_address=0.0.0.0
          root=http://web:9000
          
          [executor]
          private_key_file=/etc/zuul-executor/id_rsa
          manage_ansible=false
          
          [connection "sql"]
          driver=sql
          dburi=postgresql://zuul:super-secret@db/zuul
        dest: "{{ _volume_zuul.stdout_lines[-1] }}/zuul.conf"
        serole: object_r
        setype: container_file_t
        seuser: system_u
    - command: "echo: NotImplemented"
      name: "TODO: create fact from secret env volume content"
    - command: "podman create --name zuul-db --env=POSTGRES_PASSWORD='super-secret' --env=POSTGRES_USER='zuul' --network=host docker.io/library/postgres:12.1"
      name: "Create container"
    - file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
    - name: "Create systemd unit"
      shell: "podman generate systemd --name zuul-db > {{ ansible_user_dir }}/.config/systemd/user/zuul-db.service"
    - systemd:
        daemon_reload: true
        name: zuul-db
        scope: user
        state: started
    - command: "podman create --name zuul-zk --network=host quay.io/software-factory/zookeeper:3.4"
      name: "Create container"
    - file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
    - name: "Create systemd unit"
      shell: "podman generate systemd --name zuul-zk > {{ ansible_user_dir }}/.config/systemd/user/zuul-zk.service"
    - systemd:
        daemon_reload: true
        name: zuul-zk
        scope: user
        state: started
    - command: "podman create --name zuul-executor --privileged --volume=zuul-zuul:/etc/zuul --volume=executor-ssh-key:/etc/zuul-executor --network=host quay.io/software-factory/zuul-executor:3.4 \"zuul-executor\" \"-d\""
      name: "Create container"
    - file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
    - name: "Create systemd unit"
      shell: "podman generate systemd --name zuul-executor > {{ ansible_user_dir }}/.config/systemd/user/zuul-executor.service"
    - systemd:
        daemon_reload: true
        name: zuul-executor
        scope: user
        state: started
    - command: "podman create --name zuul-web --volume=zuul-zuul:/etc/zuul --network=host quay.io/software-factory/zuul-web:3.4 \"zuul-web\" \"-d\""
      name: "Create container"
    - file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
    - name: "Create systemd unit"
      shell: "podman generate systemd --name zuul-web > {{ ansible_user_dir }}/.config/systemd/user/zuul-web.service"
    - systemd:
        daemon_reload: true
        name: zuul-web
        scope: user
        state: started
    - command: "podman create --name zuul-scheduler --volume=zuul-zuul:/etc/zuul --volume=zuul-yaml-conf:/etc/zuul-scheduler --network=host quay.io/software-factory/zuul-scheduler:3.4 \"zuul-scheduler\" \"-d\""
      name: "Create container"
    - file:
        path: "{{ ansible_user_dir }}/.config/systemd/user"
        state: directory
    - name: "Create systemd unit"
      shell: "podman generate systemd --name zuul-scheduler > {{ ansible_user_dir }}/.config/systemd/user/zuul-scheduler.service"
    - systemd:
        daemon_reload: true
        name: zuul-scheduler
        scope: user
        state: started
