apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'enable zuul executor bwrap usage'
  name: zuul-executor
users:
# TODO: figure how to install this only for the current namespace...
- system:serviceaccount:myproject:zuul
- system:serviceaccount:default:zuul

allowPrivilegedContainer: true

# cannot set `allowPrivilegeEscalation` to false and `privileged` to true
allowPrivilegeEscalation: true

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- emptyDir
- persistentVolumeClaim
- secret
